spring:
    application:
      name: jwt

    # H2 Databaseの設定
    h2:
      console:
        enabled: true
        path: /h2-console

    datasource:
      driver-class-name: org.h2.Driver
      url: ${PROD_DB_URL}
      username: ${PROD_DB_USERNAME}
      password: ${PROD_DB_PASSWORD}

# MyBatisの設定
mybatis:
  mapper-locations: classpath:mapper/*.xml

# JWTの設定
jwt:
  secret: ${PROD_JWT_SECRET}
  expiration: 86400000 # 24時間 (ミリ秒)
